image: node:12

cache:
  paths:
    - node_modules/

stages:
  - test
  - deploy

lint-and-test:
  stage: test
  script:
    - yarn get-started
    - yarn add -D esbuild
    - yarn test
    - yarn lint
    - yarn build-all

# Deploy docs to Gitlab pages
pages:
  stage: deploy
  only:
    - master
  script:
    - yarn get-started
    - yarn docs
    - mv docs public
  artifacts:
    paths:
      - public
